# syntax=docker/dockerfile:1.0-experimental
FROM centos:7 
MAINTAINER "louisehong <louisehong4168@gmail.com>"
RUN yum install -y ipvsadm

ENTRYPOINT ["/opt/lvscare"]

ARG TARGETPLATFORM
WORKDIR /opt/

RUN --mount=target=/build tar xf /build/dist/lvscare_*_$(echo ${TARGETPLATFORM} | tr '/' '_' | sed -e 's/arm_/arm/').tar.gz

CMD ["--help"]
